/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iaybvx3SVCe
 */
import Link from "next/link"
import { Label } from "~/components/ui/label"
import { Input } from "~/components/ui/input"
import { Button } from "~/components/ui/button"

export default function login() {
  return (
    <div key="1" className="flex flex-col min-h-screen bg-[#e0f0e9]">
      <header className="flex items-center justify-between px-6 py-4">
        <Link href="/" className="text-2xl font-bold text-[#006a4e]">CaredFor</Link>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#e0f0e9]">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter text-[#006a4e] sm:text-4xl md:text-5xl lg:text-6xl/none text-center">
              Welcome to CaredFor
            </h2>
            <div className="flex flex-col items-center mt-8">
              <form className="w-full max-w-md space-y-4">
                <div className="space-y-1">
                  <Label className="text-base" htmlFor="email">Email</Label>
                  <Input id="email" required type="email" />
                </div>
                <div className="space-y-1">
                  <div className="flex justify-between">
                    <Label htmlFor="password" className="text-base">Password</Label>

                    <Link className="text-[#006a4e] hover:underline" href="#">
                      Forgot your password?
                    </Link>
                  </div>
                   
                  <Input id="password" required type="password" />
                </div>
                <Button className="w-full bg-[#006a4e] text-white hover:bg-[#00563f]" type="submit">
                  Login
                </Button>
                <div className="flex items-center justify-center gap-x-1 mt-4 text-sm">
                  <p>Don't have an account?{' '}</p>
                  <Link className="text-[#006a4e] hover:underline" href="/signup">
                    Sign up
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
