'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tXmzhc69LEs
 */
import { useFormState } from "react-dom"
import { SubmitButton } from "~/components/ui/submitButton"

// components
import { Input } from "~/components/ui/input"
import { stepOneSubmit } from "./actions"
import type { SelectUser } from "~/server/db/schema"

const initialState = {
  status: "",
  message: "",
}
export function StepOne({ email, id, isDependent }: SelectUser & { isDependent: boolean }) {
  const [state, formAction] = useFormState(stepOneSubmit, initialState)

  return (
    <div className="flex flex-col min-h-screen bg-[#e0f0e9] items-center justify-center p-4">
      <h1 className="absolute top-4 left-6 text-4xl font-bold text-[#006a4e]">CaredFor</h1>
      
      <form className="max-w-4xl w-full grid grid-cols-2 gap-8" action={formAction} >
        <input name="id" type="hidden" value={id} />

        <div className="flex flex-col min-h-[400px] space-y-6 justify-between">
          <h1 className="text-4xl font-bold text-[#155724]">
            Welcome, let&apos;s start with getting some basic information
          </h1>
          
          <div className="flex flex-col space-y-4">
            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="fullName">
                {isDependent && "Loved One's"} Full Name
              </label>
              <Input className="border border-[#c3e6cb] bg-white" id="fullName" name="fullName" placeholder="John Doe" required/>
            </div>
            
            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="phone">
                {isDependent && "Loved One's"} Phone
              </label>

              <div className="flex">
                <div className="rounded-l-lg bg-slate-50 grid place-items-center px-6 border border-[#c3e6cb] text-slate-500">
                  +1
                </div>
                <Input
                  className="block rounded-l-none border border-[#c3e6cb] bg-white dark:border-slate-800"
                  id="phone"
                  name="phone"
                  minLength={10}
                  maxLength={10}
                  required
                  placeholder="Phone number"
                />
              </div>
            </div>
            
            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="email">
                {isDependent && "Loved One's"} Email
              </label>
              <Input
                className="border border-[#c3e6cb] bg-slate-100"
                id="email"
                name="email"
                disabled={!isDependent}
                placeholder="john.doe@example.com"
                value={email ?? undefined}
                type="email"
              />
            </div>
          </div>

          <SubmitButton size="lg" className="bg-[#006a4e] text-md text-white hover:bg-[#00563f]" >
            Continue
          </SubmitButton>
          {state.status === "ERROR" && (
            <p className="text-red-500 text-center">{state.message}</p>
          )}
        </div>

        <div className="space-y-6">
          <div className="p-6 border border-[#c3e6cb] bg-white rounded-md dark:border-slate-800">
            <p className="text-lg text-[#155724]">
              Some facts about seniors living alone and feeling a uneasiness of their health and safety
            </p>
          </div>
        </div>
      </form>
    </div>
  )
}
