/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dGBYb8nfMRQ
 */
import Link from "next/link"
import { Suspense } from "react"
import { Form } from "./form"
import { Skeleton } from "./skeleton"

export default function Signup() {
  return (
    <div className="flex flex-col min-h-screen bg-[#e0f0e9]">
      <header className="flex items-center justify-between px-6 py-4">
        <Link href="/" className="text-4xl font-bold text-[#006a4e]">CaredFor</Link>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#e0f0e9]">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter text-[#006a4e] sm:text-4xl md:text-5xl lg:text-6xl/none text-center">
              Sign Up
            </h2>
            <div className="flex flex-col items-center mt-8">
              <Suspense fallback={<Skeleton />}>
                <Form />
              </Suspense>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
