'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tXmzhc69LEs
 */
import { useState } from "react"
import { useSearchParams } from "next/navigation"
import { unstable_noStore as nostore } from "next/cache"
import { useFormState } from "react-dom"
import Link from "next/link"

// components
import { Input } from "~/components/ui/input"
import { Label } from "~/components/ui/label"
import { RadioGroup, RadioGroupItem } from "~/components/ui/radio-group"

// misc
import { signup } from "./actions"
import { SubmitButton } from "~/components/ui/submitButton"

const initialState = {
  status: "",
  message: "",
}
export default function SignUp() {
  nostore()
  const searchParams = useSearchParams()
  const [password, setPassword] = useState<string>("")
  const [passwordConfirm, setPasswordConfirm] = useState<string>("")
  const [state, formAction] = useFormState(signup, initialState)

  const price = searchParams.get("price")

  return (
    <div className="flex flex-col min-h-screen bg-[#e0f0e9] items-center justify-center p-4">
      <Link href="/" className="absolute top-4 left-6 text-4xl font-bold text-[#006a4e]">CaredFor</Link>
      
      <form className="max-w-5xl w-full grid grid-cols-1 lg:grid-cols-2 gap-16 p-6" action={formAction} >
        <input type="hidden" name="price" value={price ?? ""} />
        <div className="flex flex-col min-h-[400px] space-y-6 justify-between">
          <div className="gap-y-2">
            <h1 className="text-4xl font-bold text-[#155724]">
              Welcome, let's start with some basic information
            </h1>

            <p className="text-md text-[#155724] opacity-50">
              The information provided here will only be strictly used for the purpose of the check-in calls
            </p>
          </div>
          
          <div className="flex flex-col space-y-4">
            <div className="flex flex-col space-y-3">
              <Label className="text-base text-[#006a4e]">
                I will be the one who will:
              </Label>

              <RadioGroup name="isUser" defaultValue="true">
                <div className="flex items-center space-x-2">
                  <RadioGroupItem className="text-[#155724] border-[#155724] min-h-5 min-w-5" value="true" id="isUser" />
                  <Label className="text-[#155724]" htmlFor="isUser">be receiving the check-in calls</Label>
                </div>
                <div className="flex items-center space-x-2">
                  <RadioGroupItem className="text-[#155724] border-[#155724] min-h-5 min-w-5" value="false" id="isDependent" />
                  <Label className="text-[#155724]" htmlFor="isDependent">be notified if my loved one has missed too many check-in calls</Label>
                </div>
              </RadioGroup>
            </div>
 
            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="fullName">
                Full Name
              </label>
              <Input className="border border-[#c3e6cb] bg-white" id="fullName" name="fullName" placeholder="John Doe" required/>
            </div>
            
            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="phone">
                Phone
              </label>

              <div className="flex">
                <div className="rounded-l-lg bg-slate-50 grid place-items-center px-6 border border-[#c3e6cb] text-slate-500">
                  +1
                </div>
                <Input
                  className="block rounded-l-none border border-[#c3e6cb] bg-white dark:border-slate-800"
                  id="phone"
                  name="phone"
                  minLength={10}
                  maxLength={10}
                  required
                  placeholder="Phone number"
                />
              </div>
            </div>
            
            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="email">
                Email
              </label>
              <Input
                className={`border border-[#c3e6cb] bg-white`}
                id="email"
                placeholder="john.doe@example.com"
                name="email"
                type="email"
              />
            </div>

            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="email">
                password
              </label>
              <Input
                className={`border border-[#c3e6cb] bg-white`}
                onChange={e => setPassword(e.target.value)}
                id="password"
                name="password"
                type="password"
                required
              />
            </div>

            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="email">
                confirm password
              </label>
              <Input
                className={`border border-[#c3e6cb] bg-white`}
                onChange={e => setPasswordConfirm(e.target.value)}
                id="password-confirm"
                name="password-confirm"
                type="password"
                required
              />
              {passwordConfirm && password !== passwordConfirm && <p className="text-red-500 text-sm">passwords do not match</p>}
            </div>
          </div>

          <SubmitButton
            id="step-one-submit"
            size="lg"
            className="bg-[#006a4e] text-md text-white hover:bg-[#00563f] flex items-center gap-x-1"
            disabled={password !== passwordConfirm}
          >
            Continue
          </SubmitButton>
          {state.status === "ERROR" && (
            <p className="text-red-500 text-center">{state.message}</p>
          )}
        </div>

        <div className="hidden lg:block space-y-6">
          <div className="p-6 border border-[#c3e6cb] bg-white rounded-md dark:border-slate-800">
            <p className="text-lg text-[#155724]">
              A friend of mine was telling me about this one time, when he was having lunch
              with his family, he was concerned about his grandma who was living alone.

              <br/><br/>

              She had experienced an injury and was unable to get any help until a several hours afterwards.

              <br/><br/>

              Hearing about that worried me and had me thinking about the safety and well being
              of my own grandparents.

              <br/><br/>

              The more I thought about it, the more I came to realize that there should be a
              solution for this. Which became a source of inspiration for me to create CaredFor.
            </p>
          </div>
        </div>
      </form>
    </div>
  )
}
