'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tXmzhc69LEs
 */

import { useFormState } from "react-dom"
import { stepOneSubmit } from "./actions"

// components
import { Input } from "~/components/ui/input"
import { SubmitButton } from "~/components/ui/submitButton"

const initialState = {
  status: "",
  message: "",
}
export function StepOne({ userId }: { userId: number }) {
  const [state, formAction] = useFormState(stepOneSubmit, initialState)

  return (
    <div className="flex flex-col min-h-screen bg-[#e0f0e9] items-center justify-center p-4">
      <h1 className="absolute top-4 left-6 text-4xl font-bold text-[#006a4e]">CaredFor</h1>
      
      <form className="max-w-5xl w-full grid grid-cols-1 lg:grid-cols-2 gap-16 p-6" action={formAction} >
        <div className="flex flex-col min-h-[400px] space-y-6 justify-between">
          <h1 className="text-4xl font-bold text-[#155724]">
          </h1>

          <div className="gap-y-2">
            <h1 className="text-4xl font-bold text-[#155724]">
              Let's fill in the information about your loved one
            </h1>

            <p className="text-md text-[#155724] opacity-50">
              Please fill in the information for the one who will be recieving the check-in calls<br/>
              Once again, the information provided here will strictly only be used for the purpose of the check-in calls
            </p>
          </div>
          
          <div className="flex flex-col space-y-4">
            <input type="hidden" name="userId" value={userId} />
            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="fullName">
                Full Name
              </label>
              <Input className="border border-[#c3e6cb] bg-white" id="fullName" name="fullName" placeholder="John Doe" required/>
            </div>
            
            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="phone">
                Phone
              </label>

              <div className="flex">
                <div className="rounded-l-lg bg-slate-50 grid place-items-center px-6 border border-[#c3e6cb] text-slate-500">
                  +1
                </div>
                <Input
                  className="block rounded-l-none border border-[#c3e6cb] bg-white dark:border-slate-800"
                  id="phone"
                  name="phone"
                  minLength={10}
                  maxLength={10}
                  required
                  placeholder="Phone number"
                />
              </div>
            </div>
            
            <div className="flex flex-col gap-y-1">
              <label className="block text-lg font-medium text-[#155724]" htmlFor="email">
                Email
              </label>
              <Input
                className={`border border-[#c3e6cb] bg-white`}
                id="email"
                placeholder="john.doe@example.com"
                name="email"
                type="email"
              />
            </div>
          </div>

          <SubmitButton
            id="step-one-submit"
            size="lg"
            className="bg-[#006a4e] text-md text-white hover:bg-[#00563f]"
          >
            Continue
          </SubmitButton>
          {state?.status === "ERROR" && (
            <p className="text-red-500 text-center">{state?.message}</p>
          )}
        </div>

        <div className="hidden lg:block space-y-6">
          <div className="p-6 border border-[#c3e6cb] bg-white rounded-md dark:border-slate-800">
            <p className="text-lg text-[#155724]">
              Did you know? more than five million North Americans aged over 75 years live alone!

              <br/><br/>

              Many of them see independence as an essential part of their identity, but with
              it comes an increased percentage of hardships

              <br/><br/>
              
              With Cared For, we can help them maintain their independence while providing their loved
              ones with peace of mind
            </p>
          </div>
        </div>
      </form>
    </div>
  )
}
